# Overrides for stellar theme

language:
  - zh-CN
  - en

sidebar:
  logo:
    title: '[<img no-lazy height = "64px" src="https://flintcanyon.s3.ap-southeast-1.amazonaws.com/logo4.png"/>](/)'
  menu:
    post: '[Blog](/)'
    wiki: '[Doc](/wiki/)'
    notes: '[More](/standalone/)'
    more: '[Me](/more/)'