# Overrides for stellar theme

language:
  - zh-CN
  - en

sidebar:
  logo:
    title: '[<img no-lazy height = "64px" src="https://flintcanyon.s3.ap-southeast-1.amazonaws.com/logo4.png"/>](/)'
  menu:
    post: '[Blog](/)'
    wiki: '[Doc](/wiki/)'
    notes: '[More](/standalone/)'
    more: '[Me](/more/)'

comments:
  service: waline
  waline:
    serverURL: 'https://waline-vercel-263xznfh6-fceek.vercel.app'
    locale:
      nick: "昵称*"
      mail: "邮箱*(不公开)"
      link: "网址"
      admin: "我！"
    placeholder:
    avatar: robohash
    emoji:
      - 'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/alus'